"""Initial platform schema for the SEO automation platform (v2.0).

Revision ID: 0001_initial
Revises: 
Create Date: 2026-08-21 17:39:57.228072
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001_initial'
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None



LEGACY_MVP_TABLES = (
    "websites", "pages", "audits", "seo_checks", "issues", "ai_analysis", "recommendations",
)


def _park_legacy_mvp_tables() -> None:
    """Rename pre-2.0 MVP tables to ``legacy_*`` when they are present.

    The MVP shipped ``websites`` and ``pages`` with a different shape, so creating the v2 schema
    over the top of an existing install would collide. Renaming (rather than dropping) means no
    audit history is destroyed -- an operator can inspect and drop the parked tables afterwards.

    Detection is deliberately narrow: ``audits`` only ever existed in the MVP schema, so a fresh
    install is a no-op.
    """
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing = set(inspector.get_table_names())
    if "audits" not in existing:
        return

    for table in LEGACY_MVP_TABLES:
        if table not in existing or f"legacy_{table}" in existing:
            continue
        # Renaming a table does not rename its indexes or constraints, so the old names would
        # still collide with the ones the v2 schema is about to create. Move those aside first.
        index_names = [ix["name"] for ix in inspector.get_indexes(table) if ix.get("name")]
        unique_names = [
            uc["name"] for uc in inspector.get_unique_constraints(table) if uc.get("name")
        ]
        pk = inspector.get_pk_constraint(table)
        constraint_names = unique_names + ([pk["name"]] if pk.get("name") else [])

        op.rename_table(table, f"legacy_{table}")

        if bind.dialect.name == "postgresql":
            for name in index_names:
                if not name.startswith("legacy_"):
                    op.execute(f'ALTER INDEX "{name}" RENAME TO "legacy_{name}"')
            for name in constraint_names:
                if not name.startswith("legacy_"):
                    op.execute(
                        f'ALTER TABLE "legacy_{table}" '
                        f'RENAME CONSTRAINT "{name}" TO "legacy_{name}"'
                    )


def upgrade() -> None:
    _park_legacy_mvp_tables()

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('websites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('github_repo', sa.String(length=255), nullable=True),
    sa.Column('github_branch', sa.String(length=255), nullable=True),
    sa.Column('github_path_map', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('github_framework', sa.String(length=50), nullable=True),
    sa.Column('max_pages', sa.Integer(), nullable=True),
    sa.Column('render_mode', sa.String(length=20), nullable=False),
    sa.Column('crawl_delay', sa.Float(), nullable=True),
    sa.Column('respect_robots_txt', sa.Boolean(), nullable=False),
    sa.Column('include_patterns', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('exclude_patterns', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('average_seo_score', sa.Float(), nullable=True),
    sa.Column('critical_issue_count', sa.Integer(), nullable=False),
    sa.Column('high_priority_page_count', sa.Integer(), nullable=False),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_websites_domain'), 'websites', ['domain'], unique=False)
    op.create_index(op.f('ix_websites_github_repo'), 'websites', ['github_repo'], unique=False)
    op.create_table('crawl_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('trigger', sa.String(length=30), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('target_urls', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('triggered_by_id', sa.Integer(), nullable=True),
    sa.Column('github_event_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('urls_discovered', sa.Integer(), nullable=False),
    sa.Column('pages_queued', sa.Integer(), nullable=False),
    sa.Column('pages_crawled', sa.Integer(), nullable=False),
    sa.Column('pages_rendered', sa.Integer(), nullable=False),
    sa.Column('pages_analysed', sa.Integer(), nullable=False),
    sa.Column('pages_failed', sa.Integer(), nullable=False),
    sa.Column('ai_completed', sa.Integer(), nullable=False),
    sa.Column('ai_failed', sa.Integer(), nullable=False),
    sa.Column('ai_skipped', sa.Integer(), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=True),
    sa.Column('average_seo_score', sa.Float(), nullable=True),
    sa.Column('critical_issue_count', sa.Integer(), nullable=False),
    sa.Column('total_issue_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('config_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_runs_github_event_id'), 'crawl_runs', ['github_event_id'], unique=False)
    op.create_index(op.f('ix_crawl_runs_status'), 'crawl_runs', ['status'], unique=False)
    op.create_index('ix_crawl_runs_website_created', 'crawl_runs', ['website_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_crawl_runs_website_id'), 'crawl_runs', ['website_id'], unique=False)
    op.create_table('integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('credentials_encrypted', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('account_label', sa.String(length=255), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_status', sa.String(length=30), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sync_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('website_id', 'provider', name='uq_integration_website_provider')
    )
    op.create_index(op.f('ix_integrations_provider'), 'integrations', ['provider'], unique=False)
    op.create_index(op.f('ix_integrations_status'), 'integrations', ['status'], unique=False)
    op.create_index(op.f('ix_integrations_website_id'), 'integrations', ['website_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('queue', sa.String(length=40), nullable=True),
    sa.Column('task_id', sa.String(length=100), nullable=True),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('progress_message', sa.String(length=255), nullable=True),
    sa.Column('items_total', sa.Integer(), nullable=False),
    sa.Column('items_done', sa.Integer(), nullable=False),
    sa.Column('items_failed', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_job_type'), 'jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index('ix_jobs_status_type', 'jobs', ['status', 'job_type'], unique=False)
    op.create_index(op.f('ix_jobs_task_id'), 'jobs', ['task_id'], unique=False)
    op.create_index('ix_jobs_website_created', 'jobs', ['website_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_jobs_website_id'), 'jobs', ['website_id'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('final_url', sa.String(length=2048), nullable=True),
    sa.Column('redirect_chain', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('h1', sa.Text(), nullable=True),
    sa.Column('h1_count', sa.Integer(), nullable=False),
    sa.Column('h2_count', sa.Integer(), nullable=False),
    sa.Column('h3_count', sa.Integer(), nullable=False),
    sa.Column('canonical_url', sa.String(length=2048), nullable=True),
    sa.Column('robots_directive', sa.Text(), nullable=True),
    sa.Column('lang', sa.String(length=20), nullable=True),
    sa.Column('hreflang', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('has_viewport', sa.Boolean(), nullable=False),
    sa.Column('has_structured_data', sa.Boolean(), nullable=False),
    sa.Column('structured_data_types', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('has_open_graph', sa.Boolean(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('image_count', sa.Integer(), nullable=False),
    sa.Column('missing_alt_count', sa.Integer(), nullable=False),
    sa.Column('internal_link_count', sa.Integer(), nullable=False),
    sa.Column('external_link_count', sa.Integer(), nullable=False),
    sa.Column('broken_link_count', sa.Integer(), nullable=False),
    sa.Column('inbound_internal_links', sa.Integer(), nullable=False),
    sa.Column('was_rendered', sa.Boolean(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('content_bytes', sa.Integer(), nullable=True),
    sa.Column('crawl_status', sa.String(length=30), nullable=False),
    sa.Column('crawl_error', sa.Text(), nullable=True),
    sa.Column('seo_score', sa.Float(), nullable=True),
    sa.Column('seo_category', sa.String(length=30), nullable=True),
    sa.Column('highest_severity', sa.String(length=20), nullable=True),
    sa.Column('issue_count', sa.Integer(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('priority_band', sa.String(length=10), nullable=True),
    sa.Column('priority_rank', sa.Integer(), nullable=True),
    sa.Column('ai_status', sa.String(length=30), nullable=False),
    sa.Column('ai_analysed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('website_id', 'url_hash', name='uq_page_website_url')
    )
    op.create_index(op.f('ix_pages_ai_status'), 'pages', ['ai_status'], unique=False)
    op.create_index(op.f('ix_pages_content_hash'), 'pages', ['content_hash'], unique=False)
    op.create_index(op.f('ix_pages_highest_severity'), 'pages', ['highest_severity'], unique=False)
    op.create_index(op.f('ix_pages_path'), 'pages', ['path'], unique=False)
    op.create_index(op.f('ix_pages_priority_band'), 'pages', ['priority_band'], unique=False)
    op.create_index(op.f('ix_pages_seo_category'), 'pages', ['seo_category'], unique=False)
    op.create_index(op.f('ix_pages_status_code'), 'pages', ['status_code'], unique=False)
    op.create_index('ix_pages_website_active', 'pages', ['website_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_pages_website_id'), 'pages', ['website_id'], unique=False)
    op.create_index('ix_pages_website_priority', 'pages', ['website_id', 'priority_score'], unique=False)
    op.create_index('ix_pages_website_seo_score', 'pages', ['website_id', 'seo_score'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('website_id', 'key', name='uq_setting_scope_key')
    )
    op.create_index('ix_settings_key', 'settings', ['key'], unique=False)
    op.create_index(op.f('ix_settings_website_id'), 'settings', ['website_id'], unique=False)
    op.create_table('website_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('website_id', 'user_id', name='uq_website_member')
    )
    op.create_index(op.f('ix_website_members_user_id'), 'website_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_website_members_website_id'), 'website_members', ['website_id'], unique=False)
    op.create_table('ga4_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('users', sa.Integer(), nullable=False),
    sa.Column('new_users', sa.Integer(), nullable=False),
    sa.Column('sessions', sa.Integer(), nullable=False),
    sa.Column('screen_page_views', sa.Integer(), nullable=False),
    sa.Column('engaged_sessions', sa.Integer(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('average_engagement_time', sa.Float(), nullable=False),
    sa.Column('bounce_rate', sa.Float(), nullable=False),
    sa.Column('conversions', sa.Float(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'date', name='uq_ga4_page_date')
    )
    op.create_index(op.f('ix_ga4_metrics_page_id'), 'ga4_metrics', ['page_id'], unique=False)
    op.create_index(op.f('ix_ga4_metrics_website_id'), 'ga4_metrics', ['website_id'], unique=False)
    op.create_index('ix_ga4_page_date', 'ga4_metrics', ['page_id', 'date'], unique=False)
    op.create_index('ix_ga4_website_date', 'ga4_metrics', ['website_id', 'date'], unique=False)
    op.create_table('github_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=True),
    sa.Column('delivery_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('repository', sa.String(length=255), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('before_sha', sa.String(length=64), nullable=True),
    sa.Column('after_sha', sa.String(length=64), nullable=True),
    sa.Column('pusher', sa.String(length=255), nullable=True),
    sa.Column('commit_count', sa.Integer(), nullable=False),
    sa.Column('commit_messages', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('changed_files', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('changed_file_count', sa.Integer(), nullable=False),
    sa.Column('affected_urls', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('action_taken', sa.String(length=50), nullable=True),
    sa.Column('action_reason', sa.Text(), nullable=True),
    sa.Column('crawl_run_id', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_events_action_taken'), 'github_events', ['action_taken'], unique=False)
    op.create_index(op.f('ix_github_events_delivery_id'), 'github_events', ['delivery_id'], unique=True)
    op.create_index('ix_github_events_repo', 'github_events', ['repository'], unique=False)
    op.create_index('ix_github_events_website_created', 'github_events', ['website_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_github_events_website_id'), 'github_events', ['website_id'], unique=False)
    op.create_table('gsc_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=False),
    sa.Column('position', sa.Float(), nullable=True),
    sa.Column('queries', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'date', name='uq_gsc_page_date')
    )
    op.create_index(op.f('ix_gsc_metrics_page_id'), 'gsc_metrics', ['page_id'], unique=False)
    op.create_index(op.f('ix_gsc_metrics_website_id'), 'gsc_metrics', ['website_id'], unique=False)
    op.create_index('ix_gsc_page_date', 'gsc_metrics', ['page_id', 'date'], unique=False)
    op.create_index('ix_gsc_website_date', 'gsc_metrics', ['website_id', 'date'], unique=False)
    op.create_table('historical_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('seo_score', sa.Float(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('issue_count', sa.Integer(), nullable=False),
    sa.Column('critical_count', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('users', sa.Integer(), nullable=False),
    sa.Column('sessions', sa.Integer(), nullable=False),
    sa.Column('conversions', sa.Float(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('website_id', 'page_id', 'date', 'scope', name='uq_historical_point')
    )
    op.create_index(op.f('ix_historical_metrics_website_id'), 'historical_metrics', ['website_id'], unique=False)
    op.create_index('ix_historical_page_date', 'historical_metrics', ['page_id', 'date'], unique=False)
    op.create_index('ix_historical_website_date', 'historical_metrics', ['website_id', 'date'], unique=False)
    op.create_table('priority_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('band', sa.String(length=10), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('seo_severity_component', sa.Float(), nullable=False),
    sa.Column('ga4_activity_component', sa.Float(), nullable=False),
    sa.Column('gsc_search_component', sa.Float(), nullable=False),
    sa.Column('semrush_opportunity_component', sa.Float(), nullable=False),
    sa.Column('weights', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('breakdown', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('data_sources', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('metric_window_days', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_priority_page_computed', 'priority_scores', ['page_id', 'computed_at'], unique=False)
    op.create_index(op.f('ix_priority_scores_band'), 'priority_scores', ['band'], unique=False)
    op.create_index(op.f('ix_priority_scores_page_id'), 'priority_scores', ['page_id'], unique=False)
    op.create_index(op.f('ix_priority_scores_website_id'), 'priority_scores', ['website_id'], unique=False)
    op.create_index('ix_priority_website_score', 'priority_scores', ['website_id', 'score'], unique=False)
    op.create_table('semrush_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('database', sa.String(length=10), nullable=True),
    sa.Column('organic_keywords', sa.Integer(), nullable=False),
    sa.Column('organic_traffic', sa.Integer(), nullable=False),
    sa.Column('organic_cost', sa.Float(), nullable=False),
    sa.Column('striking_distance_keywords', sa.Integer(), nullable=False),
    sa.Column('opportunity_volume', sa.Integer(), nullable=False),
    sa.Column('best_position', sa.Float(), nullable=True),
    sa.Column('average_position', sa.Float(), nullable=True),
    sa.Column('backlinks', sa.Integer(), nullable=False),
    sa.Column('referring_domains', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'date', name='uq_semrush_page_date')
    )
    op.create_index(op.f('ix_semrush_metrics_page_id'), 'semrush_metrics', ['page_id'], unique=False)
    op.create_index(op.f('ix_semrush_metrics_website_id'), 'semrush_metrics', ['website_id'], unique=False)
    op.create_index('ix_semrush_page_date', 'semrush_metrics', ['page_id', 'date'], unique=False)
    op.create_index('ix_semrush_website_date', 'semrush_metrics', ['website_id', 'date'], unique=False)
    op.create_table('seo_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crawl_run_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('seo_score', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('highest_severity', sa.String(length=20), nullable=False),
    sa.Column('issue_count', sa.Integer(), nullable=False),
    sa.Column('critical_count', sa.Integer(), nullable=False),
    sa.Column('high_count', sa.Integer(), nullable=False),
    sa.Column('medium_count', sa.Integer(), nullable=False),
    sa.Column('low_count', sa.Integer(), nullable=False),
    sa.Column('checks', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('weights_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('audited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crawl_run_id', 'page_id', name='uq_seo_audit_run_page')
    )
    op.create_index(op.f('ix_seo_audits_category'), 'seo_audits', ['category'], unique=False)
    op.create_index(op.f('ix_seo_audits_crawl_run_id'), 'seo_audits', ['crawl_run_id'], unique=False)
    op.create_index(op.f('ix_seo_audits_highest_severity'), 'seo_audits', ['highest_severity'], unique=False)
    op.create_index('ix_seo_audits_page_created', 'seo_audits', ['page_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_seo_audits_page_id'), 'seo_audits', ['page_id'], unique=False)
    op.create_index('ix_seo_audits_run_score', 'seo_audits', ['crawl_run_id', 'seo_score'], unique=False)
    op.create_table('ai_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('seo_audit_id', sa.Integer(), nullable=True),
    sa.Column('crawl_run_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('search_intent', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('expected_impact', sa.Text(), nullable=True),
    sa.Column('content_quality_score', sa.Float(), nullable=True),
    sa.Column('topic_coverage_score', sa.Float(), nullable=True),
    sa.Column('suggested_title', sa.Text(), nullable=True),
    sa.Column('suggested_meta_description', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('seo_score_at_analysis', sa.Float(), nullable=True),
    sa.Column('priority_score_at_analysis', sa.Float(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('analysed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seo_audit_id'], ['seo_audits.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_rec_page_created', 'ai_recommendations', ['page_id', 'created_at'], unique=False)
    op.create_index('ix_ai_rec_website_priority', 'ai_recommendations', ['website_id', 'priority'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_content_hash'), 'ai_recommendations', ['content_hash'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_page_id'), 'ai_recommendations', ['page_id'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_website_id'), 'ai_recommendations', ['website_id'], unique=False)
    op.create_table('seo_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seo_audit_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=100), nullable=False),
    sa.Column('check_type', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seo_audit_id'], ['seo_audits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_seo_issues_audit_severity', 'seo_issues', ['seo_audit_id', 'severity'], unique=False)
    op.create_index(op.f('ix_seo_issues_category'), 'seo_issues', ['category'], unique=False)
    op.create_index(op.f('ix_seo_issues_page_id'), 'seo_issues', ['page_id'], unique=False)
    op.create_index('ix_seo_issues_page_severity', 'seo_issues', ['page_id', 'severity'], unique=False)
    op.create_index('ix_seo_issues_rule', 'seo_issues', ['rule_id'], unique=False)
    op.create_index(op.f('ix_seo_issues_seo_audit_id'), 'seo_issues', ['seo_audit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seo_issues_seo_audit_id'), table_name='seo_issues')
    op.drop_index('ix_seo_issues_rule', table_name='seo_issues')
    op.drop_index('ix_seo_issues_page_severity', table_name='seo_issues')
    op.drop_index(op.f('ix_seo_issues_page_id'), table_name='seo_issues')
    op.drop_index(op.f('ix_seo_issues_category'), table_name='seo_issues')
    op.drop_index('ix_seo_issues_audit_severity', table_name='seo_issues')
    op.drop_table('seo_issues')
    op.drop_index(op.f('ix_ai_recommendations_website_id'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_page_id'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_content_hash'), table_name='ai_recommendations')
    op.drop_index('ix_ai_rec_website_priority', table_name='ai_recommendations')
    op.drop_index('ix_ai_rec_page_created', table_name='ai_recommendations')
    op.drop_table('ai_recommendations')
    op.drop_index('ix_seo_audits_run_score', table_name='seo_audits')
    op.drop_index(op.f('ix_seo_audits_page_id'), table_name='seo_audits')
    op.drop_index('ix_seo_audits_page_created', table_name='seo_audits')
    op.drop_index(op.f('ix_seo_audits_highest_severity'), table_name='seo_audits')
    op.drop_index(op.f('ix_seo_audits_crawl_run_id'), table_name='seo_audits')
    op.drop_index(op.f('ix_seo_audits_category'), table_name='seo_audits')
    op.drop_table('seo_audits')
    op.drop_index('ix_semrush_website_date', table_name='semrush_metrics')
    op.drop_index('ix_semrush_page_date', table_name='semrush_metrics')
    op.drop_index(op.f('ix_semrush_metrics_website_id'), table_name='semrush_metrics')
    op.drop_index(op.f('ix_semrush_metrics_page_id'), table_name='semrush_metrics')
    op.drop_table('semrush_metrics')
    op.drop_index('ix_priority_website_score', table_name='priority_scores')
    op.drop_index(op.f('ix_priority_scores_website_id'), table_name='priority_scores')
    op.drop_index(op.f('ix_priority_scores_page_id'), table_name='priority_scores')
    op.drop_index(op.f('ix_priority_scores_band'), table_name='priority_scores')
    op.drop_index('ix_priority_page_computed', table_name='priority_scores')
    op.drop_table('priority_scores')
    op.drop_index('ix_historical_website_date', table_name='historical_metrics')
    op.drop_index('ix_historical_page_date', table_name='historical_metrics')
    op.drop_index(op.f('ix_historical_metrics_website_id'), table_name='historical_metrics')
    op.drop_table('historical_metrics')
    op.drop_index('ix_gsc_website_date', table_name='gsc_metrics')
    op.drop_index('ix_gsc_page_date', table_name='gsc_metrics')
    op.drop_index(op.f('ix_gsc_metrics_website_id'), table_name='gsc_metrics')
    op.drop_index(op.f('ix_gsc_metrics_page_id'), table_name='gsc_metrics')
    op.drop_table('gsc_metrics')
    op.drop_index(op.f('ix_github_events_website_id'), table_name='github_events')
    op.drop_index('ix_github_events_website_created', table_name='github_events')
    op.drop_index('ix_github_events_repo', table_name='github_events')
    op.drop_index(op.f('ix_github_events_delivery_id'), table_name='github_events')
    op.drop_index(op.f('ix_github_events_action_taken'), table_name='github_events')
    op.drop_table('github_events')
    op.drop_index('ix_ga4_website_date', table_name='ga4_metrics')
    op.drop_index('ix_ga4_page_date', table_name='ga4_metrics')
    op.drop_index(op.f('ix_ga4_metrics_website_id'), table_name='ga4_metrics')
    op.drop_index(op.f('ix_ga4_metrics_page_id'), table_name='ga4_metrics')
    op.drop_table('ga4_metrics')
    op.drop_index(op.f('ix_website_members_website_id'), table_name='website_members')
    op.drop_index(op.f('ix_website_members_user_id'), table_name='website_members')
    op.drop_table('website_members')
    op.drop_index(op.f('ix_settings_website_id'), table_name='settings')
    op.drop_index('ix_settings_key', table_name='settings')
    op.drop_table('settings')
    op.drop_index('ix_pages_website_seo_score', table_name='pages')
    op.drop_index('ix_pages_website_priority', table_name='pages')
    op.drop_index(op.f('ix_pages_website_id'), table_name='pages')
    op.drop_index('ix_pages_website_active', table_name='pages')
    op.drop_index(op.f('ix_pages_status_code'), table_name='pages')
    op.drop_index(op.f('ix_pages_seo_category'), table_name='pages')
    op.drop_index(op.f('ix_pages_priority_band'), table_name='pages')
    op.drop_index(op.f('ix_pages_path'), table_name='pages')
    op.drop_index(op.f('ix_pages_highest_severity'), table_name='pages')
    op.drop_index(op.f('ix_pages_content_hash'), table_name='pages')
    op.drop_index(op.f('ix_pages_ai_status'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_jobs_website_id'), table_name='jobs')
    op.drop_index('ix_jobs_website_created', table_name='jobs')
    op.drop_index(op.f('ix_jobs_task_id'), table_name='jobs')
    op.drop_index('ix_jobs_status_type', table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_type'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_integrations_website_id'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_status'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_provider'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_crawl_runs_website_id'), table_name='crawl_runs')
    op.drop_index('ix_crawl_runs_website_created', table_name='crawl_runs')
    op.drop_index(op.f('ix_crawl_runs_status'), table_name='crawl_runs')
    op.drop_index(op.f('ix_crawl_runs_github_event_id'), table_name='crawl_runs')
    op.drop_table('crawl_runs')
    op.drop_index(op.f('ix_websites_github_repo'), table_name='websites')
    op.drop_index(op.f('ix_websites_domain'), table_name='websites')
    op.drop_table('websites')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
