"""Crawler accuracy: heading depth, tag multiplicity, word-count methodology.

Adds the columns needed to record H4-H6, duplicate title/description/robots tags,
canonical status, the three documented word measurements, tracking-pixel and
non-HTTP link counts, structured-data formats, and rendering/extraction errors.

Revision ID: 941852732d00
Revises: 0004_ai_impact_scores
Create Date: 2026-09-02 00:57:31.175451
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0005_crawler_accuracy_v2'
down_revision: str | None = '0004_ai_impact_scores'
branch_labels: str | None = None
depends_on: str | None = None


# Existing rows mean every NOT NULL column needs a server default; without one the ALTER is
# rejected on a populated table. The defaults are dropped afterwards so the ORM stays the single
# source of truth for new rows.
BACKFILLED_INTEGER_COLUMNS = (
    "h4_count", "h5_count", "h6_count", "empty_heading_count", "title_count",
    "meta_description_count", "meta_robots_count", "raw_word_count",
    "visible_word_count", "main_content_word_count", "tracking_pixel_count",
    "non_http_link_count",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('h4_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('pages', sa.Column('h5_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('pages', sa.Column('h6_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('pages', sa.Column('empty_heading_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('pages', sa.Column('title_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('pages', sa.Column('meta_description_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('pages', sa.Column('meta_robots_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('pages', sa.Column('canonical_status', sa.String(length=20), nullable=True))
    op.add_column('pages', sa.Column('raw_word_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('pages', sa.Column('visible_word_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('pages', sa.Column('main_content_word_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('pages', sa.Column('content_scope', sa.String(length=20), nullable=True))
    op.add_column('pages', sa.Column('tracking_pixel_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('pages', sa.Column('non_http_link_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('pages', sa.Column('structured_data_formats', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('pages', sa.Column('render_error', sa.Text(), nullable=True))
    op.add_column('pages', sa.Column('extraction_errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.alter_column('pages', 'sponsored_link_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('pages', 'ugc_link_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('pages', 'canonical_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('pages', 'empty_alt_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('pages', 'crawl_quality',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


    # The defaults existed only to backfill; new rows get their value from the ORM.
    for column in BACKFILLED_INTEGER_COLUMNS:
        op.alter_column("pages", column, server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pages', 'crawl_quality',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'ok'::character varying"),
               existing_nullable=False)
    op.alter_column('pages', 'empty_alt_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('pages', 'canonical_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('pages', 'ugc_link_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('pages', 'sponsored_link_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_column('pages', 'extraction_errors')
    op.drop_column('pages', 'render_error')
    op.drop_column('pages', 'structured_data_formats')
    op.drop_column('pages', 'non_http_link_count')
    op.drop_column('pages', 'tracking_pixel_count')
    op.drop_column('pages', 'content_scope')
    op.drop_column('pages', 'main_content_word_count')
    op.drop_column('pages', 'visible_word_count')
    op.drop_column('pages', 'raw_word_count')
    op.drop_column('pages', 'canonical_status')
    op.drop_column('pages', 'meta_robots_count')
    op.drop_column('pages', 'meta_description_count')
    op.drop_column('pages', 'title_count')
    op.drop_column('pages', 'empty_heading_count')
    op.drop_column('pages', 'h6_count')
    op.drop_column('pages', 'h5_count')
    op.drop_column('pages', 'h4_count')
    # ### end Alembic commands ###
